# Generated by Django 4.1.2 on 2022-10-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={},
        ),
    ]
