# Generated by Django 4.1.2 on 2022-11-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': (('can_view_StaffProfile__name', 'Can view StaffProfile name'), ('can_change_StaffProfile__name', 'Can change StaffProfile name'), ('can_view_StaffProfile__address', 'Can view StaffProfile address'), ('can_change_StaffProfile__address', 'Can change StaffProfile address'), ('can_view_StaffProfile__postal_code', 'Can view StaffProfile postal_code'), ('can_change_StaffProfile__postal_code', 'Can change StaffProfile postal_code'), ('can_view_StaffProfile__country', 'Can view StaffProfile country'), ('can_change_StaffProfile__country', 'Can change StaffProfile country'), ('can_view_StaffProfile__profile_picture', 'Can view StaffProfile profile_picture'), ('can_change_StaffProfile__profile_picture', 'Can change StaffProfile profile_picture'))},
        ),
    ]
