# Generated by Django 4.1.2 on 2022-10-26 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_adminprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAndPhoneOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('otp', models.CharField(db_index=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
