# Generated by Django 4.1.2 on 2022-10-26 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_emailandphoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('otp', models.CharField(db_index=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailAndPhoneOtp',
        ),
    ]
