# Generated by Django 4.1.2 on 2022-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_phoneotp_delete_emailandphoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='customer_profile_picture/'),
        ),
    ]
