# Generated by Django 4.1.2 on 2022-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_alter_customerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number_history',
            field=models.JSONField(default=list),
        ),
    ]
