# Generated by Django 4.1.2 on 2022-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_customerprofile_email_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
