# Generated by Django 4.1.2 on 2022-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0012_phoneotp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_providers',
            field=models.JSONField(default=list),
        ),
    ]
