# Generated by Django 4.1.2 on 2022-11-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_module_permission_modulepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(max_length=255, verbose_name='admin_role'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, verbose_name='module_name'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='permission_name'),
        ),
    ]
