# Generated by Django 4.1.2 on 2022-11-13 14:21

from django.db import migrations, models
from utils.default_content_and_attribute import CONTENTS


def add_group_and_permission(apps, schema_editor):
    content_type = apps.get_model('contenttypes', 'ContentType')
    permission = apps.get_model('auth', 'Permission')
    
    for content in CONTENTS:
        new_content = content_type.objects.create(app_label=content['app_label'],model=content['model'])
        if content['permissions']:
            print('new content:', new_content)
            for content_permission in content['permissions']:
                permission.objects.create(name=content_permission['name'],
                content_type = new_content, codename=content_permission['codename'])

class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_alter_adminrole_name_alter_module_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulepermission',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulepermission',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='modulepermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='roles',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'staff'), (3, 'super admin')]),
        ),
        migrations.DeleteModel(
            name='AdminRole',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RunPython(add_group_and_permission),
    ]
