# Generated by Django 4.1.2 on 2022-11-14 05:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from utils.default_content_and_attribute import CONTENTS


def add_group_and_permission(apps, schema_editor):
    content_type = apps.get_model('contenttypes', 'ContentType')
    custom_permission = apps.get_model('custom_auth', 'CustomPermission')
    
    for content in CONTENTS:
        new_content = content_type.objects.create(app_label=content['app_label'],model=content['model'])
        if content['permissions']:
            print('new content:', new_content)
            for content_permission in content['permissions']:
                custom_permission.objects.create(name=content_permission['name'],
                content_type = new_content, codename=content_permission['codename'], attribute_name=content_permission['attribute_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0017_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
                ('attribute_name', models.CharField(blank=True, max_length=100)),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.RunPython(add_group_and_permission),
    ]
